### DISCUSSION TITLE
Any reason for not adding this to the "Official add-ons"?

### DISCUSSION THREAD

**Discussion by LeoCal** [hassio-addons/addon-mopidy#117] [Q&A]
Hi,

Any reason for not adding this to the "Official add-ons"?
I see some changes have been made to mopidy addon in GitHub this year, so I was wondering whether this is ready to be added to the official addons or it needs any additional work to get it working? 

Thanks

**Comment by frenck** [comment]
Just not stable enough imho, too many things people can run into.

**Comment by LeoCal** [comment]
I see, thanks for the quick reply!

Is there any other server that one could add as add-on to home assistant to have a fully fledged MP3 server like mopidy? Maybe a MPD based one?

**Reply by frenck** [reply]
Not aware of that.

**Reply by Rapace29** [reply]
for MPD, look at https://github.com/Poeschl/Hassio-Addons ( simple to install and work well )
just need a iframe to be perfect

```
# configuration.yaml example
# https://community.home-assistant.io/t/when-i-click-on-custom-link-added-via-panel-iframe-it-opens-the-link-but-then-creates-a-second-sidebar/208032/3
    
panel_custom:
  - name: panel-redirect
    # url_path needs to be unique for each panel_custom config
    url_path: redirect-states
    sidebar_title: 'Music'
    sidebar_icon: mdi:music
    module_url: /local/panel-redirect.js
    config:
      # Where you want to redirect to
      target: hassio/ingress/243ffc37_mpd
```
