### ISSUE TITLE
Snapcast integration Disconnected

### ISSUE THREAD

**Issue by gitisz** [hassio-addons/addon-mopidy#103]
# Problem/Motivation

Mopidy-Iris has integration with Snapcast, however from Settings I see the Snapserver is in a disconnected state

## Expected behavior

When you provide the Snapcast server host and port (1780) Mopidy-Iris should connect.

## Actual behavior

With a Snapcast docker container loaded in the Home Assistant host (using Portainer for example), the Snapcast server is accessible, however Mopidy-Iris is unable to discover the Snapcast server. 

![image](https://user-images.githubusercontent.com/4492953/108603755-c21e4c00-7377-11eb-9829-e21d466e82f3.png)

## Steps to reproduce

In Portainer create a new stack with the following docker-compose config:
```
snapserver:
    image: "docker-registry/snapserver"
    ports:
        - "1704:1704"
        - "1705:1705"
        - "1780:1780"
    volumes:
        - fifo:/tmp/snapcast/
 ```

Snapserver container can be pulled from `https://hub.docker.com/r/ivdata/snapserver` or build your own from `https://github.com/IVData/dockerfiles/tree/master/snapserver`
