### ISSUE TITLE
Mopidy-Spotify extension is not running - you will not be able to play any Spotify tracks

### ISSUE THREAD

**Issue by rqsakai** [hassio-addons/addon-mopidy#213]
# Problem/Motivation
I was able to install modipy in my hassio, but I get the following error while setting up Spotify

Mopidy-Spotify extension is not running - you will not be able to play any Spotify tracks

## Expected behavior
I should be able to connect to spotify

## Actual behavior
Not connecting

## Steps to reproduce

1. Install Modipy
2. configure python plugin Mopidy-Spotify
3. configure API tokens

YAML config example:"
```
python_packages:
  - Mopidy-Spotify
settings:
  - name: spotify/enabled
    value: "true"
  - name: file/enabled
    value: "true"
  - name: file/media_dirs
    value: /share/mopidy/media
  - name: spotify/client_id
    value: ********************************************
  - name: spotify/client_secret
    value: ********************************************=
system_packages: []
```

How can we properly configure this integration?
